### ISSUE TITLE
I tried to bump version..

### ISSUE THREAD

**Issue by Rast1234** [chylex/Better-Controls#31]
Hi. Sorry to bother you, maybe you'll give me a hint. The mod did not load for Minecraft 1.20.6 with NeoForge 20.6.x. I attempted to recompile it, bumping versions in gradle config accordingly, but toolchain breaks because of new Java version. I tried to fix that too and got it to compile (also had to comment out a missing/moved method call) but NeoForm codegen still fails, again because of new Java version.

Any ideas appreciated, maybe i'm missing something or just doing it wrong. I'm not familiar with gradle and minecraft toolchain unfortunately. You can see my changes here: https://github.com/chylex/Better-Controls/compare/main...Rast1234:Better-Controls:main

Relevant stacktrace from `gradlew build`:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
        at net.minecraftforge.accesstransformer.TransformerProcessor.lambda$processJar$3(TransformerProcessor.java:108)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at net.minecraftforge.accesstransformer.TransformerProcessor.processJar(TransformerProcessor.java:104)
        at net.minecraftforge.accesstransformer.TransformerProcessor.main(TransformerProcessor.java:81)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':NeoForge:neoFormApplyForgesAccessTransformer'.
> Process 'command 'C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot\bin\java.exe'' finished with non-zero exit value 1

```

**Comment by chylex** [comment]
Updated to 1.20.5/6.

**Comment by Rast1234** [comment]
thank you! i see recent commits, it wasnt that simple
